import { writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import type { ResolvedDependency, ManualResource } from "../resolvers/types.js";

function renderDependency(dep: ResolvedDependency): string {
  const lines: string[] = [`### ${dep.info.name}`];

  for (const source of dep.sources) {
    switch (source.type) {
      case "llms-txt":
        lines.push(`- **llms.txt**: ${source.url}`);
        break;
      case "context7":
        lines.push(`- **Context7**: \`${source.identifier}\``);
        break;
      case "mcp":
        if (source.endpoint) lines.push(`- **MCP**: endpoint \`${source.endpoint}\``);
        if (source.command) lines.push(`- **MCP**: \`${source.command}\``);
        break;
      case "docs-url":
        lines.push(`- **Docs**: ${source.url}`);
        break;
    }
  }

  if (dep.sources.length === 0) {
    lines.push("- **No documentation sources found**");
  }

  return lines.join("\n");
}

function renderResource(resource: ManualResource): string {
  const lines: string[] = [`### ${resource.name}`];

  switch (resource.type) {
    case "skill":
      lines.push(`- **Skill**: ${resource.url}`);
      break;
    case "docs":
      lines.push(`- **Docs**: ${resource.url}`);
      break;
    case "file":
      lines.push(`- **File**: ${resource.path}`);
      break;
  }

  return lines.join("\n");
}

export function generateIndexContent(
  deps: ResolvedDependency[],
  resources: ManualResource[] = [],
): string {
  const withDocs = deps.filter((d) => d.sources.length > 0).length;

  const sections: string[] = [
    "# Documentation Index",
    "> Auto-generated by agent-docs. Do not edit manually.",
    "> Run `npx agent-docs update` to refresh, or use the agent-docs MCP `update` tool.",
    ">",
    "> If you notice a dependency that isn't listed here, run `npx agent-docs init` to rescan.",
    "",
    "## Dependencies",
    "",
  ];

  for (const dep of deps) {
    sections.push(renderDependency(dep));
    sections.push("");
  }

  if (resources.length > 0) {
    sections.push("## Resources");
    sections.push("");
    for (const resource of resources) {
      sections.push(renderResource(resource));
      sections.push("");
    }
  }

  sections.push("---");
  const resourceNote = resources.length > 0 ? ` ${resources.length} manual resources.` : "";
  sections.push(
    `*${deps.length} dependencies scanned, ${withDocs} with documentation sources found.${resourceNote}*`,
  );
  sections.push("");

  return sections.join("\n");
}

export async function writeIndex(
  projectDir: string,
  content: string,
): Promise<string> {
  const indexPath = join(projectDir, ".agent-docs", "index.md");
  await mkdir(dirname(indexPath), { recursive: true });
  await writeFile(indexPath, content, "utf-8");
  return indexPath;
}
